apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-pipelinerun
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelinerun", "taskrun"]
  verbs: ["get","list","watch","create","update","delete","patch"]