apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-mvnbuild-pushimage-run
spec:
  pipelineRef:
    name: pipeline-portal
  serviceAccountName: takton-sa
  params:
  - name: repo-url
    value: "git@github.com/donginjeong/tekton.git"
  - name: branch-name
    value: "main"
  - name: maven-goal
    value: "package"
  - name: image-name
    value: "docker.io/jdi0901/vtwsaas"
  - name: image-tag
    value: "latest"
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: shared-ssh-dir
    secret:
      secretName: ssh-key-secret
  - name: docker-config
    secret:
      secretName: regcred